version: "3.8"

services:
  streamlit_app:
    build: ./streamlit_app
    ports:
      - "8501:8501"
    depends_on:
      - flask_backend
    networks:
      - app-network
    environment:
      - FLASK_API_URL=http://flask_backend:1818

  flask_backend:
    build: ./flask_backend
    ports:
      - "1818:1818"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
